apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-configmap
  annotations:
    avp.kubernetes.io/path: "secret/data/sample-app" # Placeholder for Vault integration later.
data:
  sample-config.toml: |
    {{ .Files.Get "files/sample-config.toml" }}

