apiVersion: v1
kind: Secret
metadata:
  name: sample-secret
  annotations:
    avp.kubernetes.io/path: "secret/data/sample-app" # Vault path.
type: Opaque
data:
  sample-config.toml: |
    {{ .Files.Get "files/sample-config.toml" | nindent 4 | b64enc }}
